### ISSUE TITLE
Example notebook and comments in the code not present

### ISSUE THREAD

**Issue by amoeez** [ESRG-IST/K-NearestNeighbour#1]
Can you include an example notebook in your repository to show the working of module? Moreover, it would be convenient if you can include some comments in your work. Thank you

**Comment by MAzeemAhmad** [comment]
Dear Sir, I have added on example in a notebook with comments. It's dataset has also been added.
Thank you for the guidance

> Can you include an example notebook in your repository to show the working of module? Moreover, it would be convenient if you can include some comments in your work. Thank you
